### ISSUE TITLE
2022.4-b4280 release

### ISSUE THREAD

**Issue by davekeeshan** [TUT-ASI/leon3-grlib-gpl-mirror#4]
Hey A note to say there is a new release from gaisler:

https://www.gaisler.com/products/grlib/grlib-gpl-2022.4-b4280.tar.gz

I tried to run the raku script found here:

https://github.com/TUT-ASI/leon3-grlib-gpl-mirror/pull/2#issuecomment-1099532268

It seemed to bomb out when it tried to fetch the zip file over curl.  I compile rakudo from source today, so I am unsure if the permissions and every thing are working

**Comment by AlexDaniel** [comment]
Done! I guess I should simply automate it so that it runs regularly :)

**Comment by davekeeshan** [comment]
Excellent, thanks for that.

Yeah a nightly cron somewhere could do the job. I have been looking as github actions a lot there might be a way to automate it there.

**Comment by AlexDaniel** [comment]
@davekeeshan I think I've been keeping up with the latest updates relatively fine. Let me know if there's an unwanted delay at any point!

**Comment by davekeeshan** [comment]
I will do, I noticed it a few days ago alright, but I didn't want to get on your case too much, I was going to ping you later in the week.

Thanks for maintaining this release, I find it very helpful.
