### ISSUE TITLE
2023.4-b4288 release

### ISSUE THREAD

**Issue by davekeeshan** [TUT-ASI/leon3-grlib-gpl-mirror#5]
Sorry I have been a little busy, but i noticed there was a new release last month:

[grlib-gpl-2023.4-b4288.tar.gz](https://www.gaisler.com/products/grlib/grlib-gpl-2023.4-b4288.tar.gz)

**Comment by AlexDaniel** [comment]
Oh, yeah, I've been a little bit away. Will be back on Friday and will push the change. I also have some new infra that can automate this a lot easier, so I will take a look a bit later once I get rid of other personal backlog items :)

**Comment by AlexDaniel** [comment]
They have made some changes to the website, so the script needed a small tweak. Now it's all good and up to date! Full automation will come a bit later.

Thank you so much for notifying me! I hope you find this repo useful!
